### ISSUE TITLE
remove-node-modules deleted entire directory

### ISSUE THREAD

**Issue by Atinjanki** [studio174/node-cleanup#4]
I gave path to the folder where my angular projects where, to delete node_nodules and it deleted entire folder.

**Comment by j-quelly** [comment]
@Atinjanki Where did you execute the script from?

**Comment by Atinjanki** [comment]
Hi,
I executed the script in the folder that had 8-10 angular projects in it.

**Comment by j-quelly** [comment]
That's not very helpful, 

1. Can you provide a better example?  
2. What did you type into your terminal?
3. What were the expected results?

**Comment by bphkns** [comment]
It deletes the entire directory. For eg while I ran this it deleted my whole `CODE` folder `remove-node-modules CODE`

**Comment by j-quelly** [comment]
> It deletes the entire directory. For eg while I ran this it deleted my whole `CODE` folder `remove-node-modules CODE`

It's doing exactly what you instructed it to do. `CODE` is not the path to your node_modules folder
